name: Build Images

on:
  push:
    branches: [ main ]

jobs:
  general-purpose:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Quay.io
        uses: docker/login-action@v3 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}
      -
        name: Push to Quay.io
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:general-purpose"
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
          tags: quay.io/fesehemalige/general-purpose:latest
