name: Build Derived Images

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:
  push:

jobs:
  redmine:
    runs-on: ubuntu-latest
    steps:

      - name: Query latest Bitnami Redmine version
        id: check_version
        run: |
          latest_version=$(curl -s https://hub.docker.com/v2/repositories/bitnami/redmine/tags | jq -r '.results | map(select(.name | test("^\\d+\\.\\d+\\.\\d+-debian"))) | .[0].name')
          echo "latest_version=${latest_version}" >> $GITHUB_ENV
          echo "$latest_version" > .latest_version

      - name: Set up Cache
        id: cache
        uses: actions/cache@v3
        with:
          key: ${{ env.latest_version }}
          path: .latest_version
          lookup-only: true

      - name: Set up Docker Buildx
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}

      - name: Push to Quay.io
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:redmine"
          push: true
          tags: quay.io/fesehemalige/redmine:${{ env.latest_version }}
          build-args: |
            TAG=${{ env.latest_version }}
